### ISSUE TITLE
compatibility with django-constance

### ISSUE THREAD

**Issue by sobolevn** [divio/djangocms-admin-style#387]
I have found a small issue with `django-constance`.

Here's how it looks now:
<img width="1272" alt="2017-04-20 22 49 44" src="https://cloud.githubusercontent.com/assets/4660275/25249743/ae1a5d50-261b-11e7-9c8e-c6efa5a13e5c.png">

It all happens because of these lines:

```css
.change-list #changelist table tbody td, .change-list #changelist table tbody th {
  white-space: nowrap;
}
```

If I change it to:

```css
.change-list #changelist table tbody td, .change-list #changelist table tbody th {
  white-space: normal;  /* some others work too */
}
```

It all starts to work fine:
<img width="1278" alt="2017-04-20 22 52 27" src="https://cloud.githubusercontent.com/assets/4660275/25249836/100c8614-261c-11e7-81ed-97ee91bd81ce.png">

I am using these versions:

django-cms==3.4.2
django-constance[database]==2.0.0
djangocms-admin-style==1.2.6.2  # via django-cms
